# Generated by Django 4.2.5 on 2023-09-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_user_info_user_address_user_info_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_gender',
            field=models.CharField(default='Select an option', max_length=10),
        ),
    ]
