# Generated by Django 4.2.5 on 2023-09-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_user_info_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_profile',
            field=models.ImageField(upload_to='web_images'),
        ),
    ]
