# Generated by Django 4.2.5 on 2023-09-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_user_info_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_profile',
            field=models.ImageField(default='images/defaultpf.jpg', upload_to='web_images'),
        ),
    ]
