# Generated by Django 4.2.5 on 2023-09-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_user_info_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='user_phone',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
    ]
