# Generated by Django 4.2.5 on 2023-09-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_user_info_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
