# Generated by Django 4.2.5 on 2023-09-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_user_info_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='slug',
        ),
    ]
