# Generated by Django 4.2.5 on 2023-09-08 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_user_info_slug_alter_user_info_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Product_Id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_image', models.ImageField(default='images/imagenotfound.png', upload_to='web_images/store')),
                ('product_description', models.TextField(default='Description not available', max_length=100)),
                ('product_rating', models.FloatField(max_length=10)),
                ('product_price', models.FloatField(max_length=10)),
                ('product_discount', models.IntegerField(default=0, max_length=2)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_name', to='store.category')),
                ('product_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.product_id')),
            ],
        ),
    ]
