# Generated by Django 4.2.5 on 2023-09-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_product_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='web_images/store/imagenotfound.png', upload_to='web_images/store'),
        ),
    ]
