# Generated by Django 4.2.5 on 2023-09-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='user_profile',
            field=models.ImageField(default='web_images/store/defaultpf.jpg', upload_to='web_images'),
        ),
    ]
