# Generated by Django 4.2.5 on 2023-09-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_user_info_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
