# Generated by Django 4.2.5 on 2023-09-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_user_info_featured_product_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='web_images/store/E-Commerce Facebook Ad.png', upload_to='web_images/store/banner')),
            ],
        ),
    ]
