# Generated by Django 4.2.5 on 2023-09-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_order_orderid_orderitem_order_orderid_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
