# Generated by Django 4.2.5 on 2023-09-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_orderitem_order_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderid',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='OrderId',
        ),
    ]
