# Generated by Django 4.2.5 on 2023-09-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_order_orderid_delete_orderid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='orderid',
        ),
    ]
