# Generated by Django 4.2.5 on 2023-09-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_rename_order_orderitem_orderid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='orderid',
            new_name='order',
        ),
    ]
