# Generated by Django 4.2.5 on 2023-09-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_rename_orderid_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='city',
        ),
    ]
